# Generated by Django 4.1.7 on 2023-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
