# Generated by Django 4.1.7 on 2023-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('occasion', models.CharField(blank=True, max_length=15, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('table_no', models.PositiveIntegerField(default=0)),
                ('review_message', models.TextField()),
                ('confirm_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
