# Generated by Django 4.1.7 on 2023-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_booktable_delete_customermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.PositiveIntegerField()),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
            ],
        ),
    ]
