# Generated by Django 4.1.7 on 2023-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0005_foodcategories_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='category_name',
            field=models.CharField(max_length=30),
        ),
    ]
