# Generated by Django 4.1.7 on 2023-03-11 18:56

import authority.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0006_alter_foodcategories_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetMenuFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=authority.utils.food_directory_path)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SetMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30)),
                ('menu_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to=authority.utils.set_menu_directory_path)),
                ('other_image', models.ImageField(upload_to=authority.utils.set_menu_directory_path)),
                ('price', models.PositiveIntegerField()),
                ('offer_percentage', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('SetMenuFood', models.ManyToManyField(related_name='menu_food', to='authority.setmenufood')),
                ('food_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='authority.foodcategories')),
            ],
        ),
    ]
