# Generated by Django 4.1.7 on 2023-03-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0007_setmenufood_setmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmenufood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='setmenufood',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setmenufood',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
