# Generated by Django 4.1.7 on 2023-03-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0008_setmenufood_created_at_setmenufood_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmenu',
            name='other_image',
        ),
    ]
