# Generated by Django 4.1.7 on 2023-03-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0009_remove_setmenu_other_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setmenu',
            old_name='SetMenuFood',
            new_name='foods_items',
        ),
    ]
