# Generated by Django 4.1.7 on 2023-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0011_rename_main_image_setmenu_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people'), (9, '9 people'), (10, '10 people'), (11, '11 people'), (12, '12 people'), (13, '13 people'), (14, '14 people'), (15, '15 people'), (16, '16 people'), (17, '17 people'), (18, '18 people'), (19, '19 people'), (20, '20 people')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Anniversary', 'Anniversary'), ('Business Meal', 'Business Meal'), ('Dinner', 'Dinner'), ('Other', 'Other')], max_length=15)),
                ('messages', models.TextField()),
                ('table_no', models.PositiveIntegerField()),
                ('review_message', models.TextField()),
            ],
        ),
    ]
