# Generated by Django 4.1.7 on 2023-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0012_booktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='occasion',
            field=models.CharField(blank=True, choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Anniversary', 'Anniversary'), ('Business Meal', 'Business Meal'), ('Dinner', 'Dinner'), ('Other', 'Other')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='table_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
