# Generated by Django 4.1.7 on 2023-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0013_alter_booktable_messages_alter_booktable_occasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='party_size',
            field=models.CharField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people'), (9, '9 people'), (10, '10 people'), (11, '11 people'), (12, '12 people'), (13, '13 people'), (14, '14 people'), (15, '15 people'), (16, '16 people'), (17, '17 people'), (18, '18 people'), (19, '19 people'), (20, '20 people')], max_length=50),
        ),
    ]
