# Generated by Django 4.1.7 on 2023-03-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0014_alter_booktable_party_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='last_name',
        ),
    ]
