# Generated by Django 4.1.7 on 2023-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0015_rename_first_name_booktable_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='occasion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='party_size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
