# Generated by Django 4.1.7 on 2023-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0016_alter_booktable_occasion_alter_booktable_party_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='confirm_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booktable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
