# Generated by Django 4.1.7 on 2023-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0017_booktable_confirm_status_booktable_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='confirm_status',
            field=models.BooleanField(default=False),
        ),
    ]
