# Generated by Django 4.1.7 on 2023-03-25 20:40

from django.db import migrations, models
import django.db.models.deletion
import products.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('sort_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to=products.utils.category_directory_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=products.utils.food_directory_path)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30)),
                ('menu_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_description', models.TextField(blank=True, null=True)),
                ('menu_image', models.ImageField(upload_to=products.utils.set_menu_directory_path)),
                ('price', models.PositiveIntegerField()),
                ('offer_percentage', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('food_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='products.foodcategories')),
                ('foods_items', models.ManyToManyField(blank=True, null=True, related_name='menu_food', to='products.menufood')),
            ],
        ),
    ]
