# Generated by Django 4.1.7 on 2023-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='foods_items',
            field=models.ManyToManyField(blank=True, related_name='menu_food', to='products.menufood'),
        ),
    ]
