# Generated by Django 4.1.7 on 2023-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
