# Generated by Django 4.1.7 on 2023-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_order_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
